# Output Prediction

***Predict the exact output of the given code snippets. Explain the underlying Pandas operation wherever required.***


# Q1.  Array operations and vectorization

import numpy as np

import pandas as pd

arr = np.array([10, 20, 30])

s = pd.Series([10, 20, 30])

print(arr * 2)

print(s * 2)

***1.Predict the output of both statements.***

output for print(arr * 2) is

 [20 40 60]

output for print(s * 2)  is 

0    20

1    40

2    60

dtype: int64

***2.Identify one similarity and one difference between the two data structures***

Similarity:
Both NumPy arrays and Pandas Series support element-wise operations. Multiplying by 2 multiplies every element by 2.

Difference:
A NumPy array mainly stores values, while a Pandas Series stores values along with an index.



# Q2. Boolean Filtering

import pandas as pd

df = pd.DataFrame({

    'Student': ['A', 'B', 'C', 'D'],

    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks’]])

***1.Predict the rows displayed.***

According to the condition Students B, C, and D are displayed because their marks are greater than or equal to 65, so the resulting DataFrame has 3 rows and 2 columns. 

     Student  Marks

1       B       80

2       C       65

3       D       90


***2.How many rows and columns will the resulting DataFrame contain?***

The rows and columns the result contain:

3 rows

2 columns



# Q3.  Descriptive statistics

import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())

print(df['Marks'].max())

print(df['Marks'].median())

***1.Predict all three outputs.***

Output:

30.0

50

30.0


***2.Explain how the median differs from the mean.***


The mean is the average of all values, while the median is the middle value after sorting the data.




# Q4.  Group-wise Analysis

import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())


***1.Predict the output.***

Output

Department

HR    40000.0

IT    50000.0

Name: Salary, dtype: float64

***2.Explain how groupby() calculates the department-wise average.***



groupby() groups the data by department and calculates the average salary for each department: HR = (30000 + 50000)/2 = 40000, IT = (40000 + 60000)/2 = 50000


# Q5.   Pandas Correlation - Positive

import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks’]))

***1.Predict the correlation coefficient.***

Output:

1.0


***2.Interpret the direction and strength of the relationship.***



There is a perfect positive correlation, meaning as study hours increase, marks increase proportionally.


# Q6.  Pandas Correlation - Negative

import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))

***1.Predict the correlation coefficient.***

Correlation coefficient:

-1.0

***2.Explain what the sign of the coefficient indicates about the relationship.***



The negative sign indicates an inverse relationship: as Price increases, Demand decreases, and -1.0 shows a perfect negative correlation.


# Code Correction

# Q1. JSON and CSV          

import pandas as pd

df = pd.read_csv("students.csv", header=None)

print(df)    

***1.A CSV file contains a header row, but the following code incorrectly reads the first student's record as column names. Correct the code.***

If the CSV file contains a header row, use the default header=0 or simply omit header=None.

header=None tells Pandas that the CSV has no header, so the first row becomes data; removing it allows Pandas to correctly use the first row as column names.

import pandas as pd

df = pd.read_csv("students.csv")

print(df)



# Q2. Data Analysis

import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary').head(5))                              

***1.The objective is to display the five highest salaries from a DataFrame. Correct the code.***


sort_values() sorts in ascending order by default, so head(5) returns the five lowest salaries, not the highest.

ascending=False sorts salaries from highest to lowest, so head(5) gives the five highest salaries.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


 # Q3. Cleaning Data       

import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'].fillna(df['Marks'].mean())
print(df)    

***1.A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code.***

fillna() returns a new Series but does not modify the original DataFrame unless you assign the result back.

Assigning the result back to df['Marks'] updates the missing value with the mean (80).




In [2]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

   Marks
0   70.0
1   80.0
2   90.0


# Q4. Correlation

import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df.corr('Hours', 'Marks’))

***1.The objective is to calculate the correlation between Hours and Marks. Correct the code.***

DataFrame.corr() does not take column names as arguments like this.

df['Hours'].corr(df['Marks']) calculates the correlation between the Hours and Marks columns


In [3]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


# Edge Cases

# Q1. Two NumPy arrays have shapes (3, 1) and (1, 3). Predict the shape of their element-wise sum and explain how broadcasting works. Why might the result differ from adding two one-dimensional arrays?

import numpy as np

a = np.array([[10], [20], [30]])

b = np.array([[1, 2, 3]])

result = a + b

print(result)

print(result.shape)

***1.Predict the output of the given code.***

[[11 12 13]

 [21 22 23]
 
 [31 32 33]]

(3, 3)

***2.Identify the shapes of arrays a and b before addition.***

a has 3 rows and 1 column

b has 1 row and 3 columns

***3.Explain how NumPy broadcasting enables the addition of these arrays.***

NumPy automatically expands the smaller dimensions to make the shapes compatible.
Conceptually:

a:                 b:

10                 1  2  3

20       +        1  2  3

30                1  2  3

So the addition becomes:

10+1   10+2   10+3

20+1   20+2   20+3

30+1   30+2   30+3

Result:

[[11 12 13]

 [21 22 23]

 [31 32 33]]

***4.What would happen if b were replaced with np.array([1, 2])? Explain the reason.***

NumPy broadcasts b from (2,) to (1, 2) and a from (3,1) across the columns.

NumPy compares dimensions from right to left.b has only 2 elements, but because a has 1 column, NumPy can broadcast that single column to match the 2 elements of b. Therefore, the addition is valid and produces a (3, 2) array.



# Q2. A CSV file contains commas inside quoted text fields, missing values, and dates in different formats. Explain how incorrect parsing can affect the resulting DataFrame and identify suitable read options or preprocessing steps.

Given dataset: students.csv

ID,Name,Date,Marks

101,"Asha, R",2026-09-01,80

102,Ravi,01/09/2026,

103,Neha,2026-09-03,NA

Given code:

import pandas as pd

df = pd.read_csv("students.csv")

print(df)

print(df.dtypes)

***1.Predict how the quoted comma in "Asha, R" will be handled when the CSV file is read.***

The value is enclosed in double quotes, so pandas recognizes the comma as part of the Name field rather than as a column separator.


So, the comma in "Asha, R" will not create an extra column

***2.Identify the potential issues with the Date and Marks columns.***

Date column:

The dates are in different formats

2026-09-01

01/09/2026

2026-09-03

Pandas may initially read them as object/string values rather than a proper datetime type.


Marks column

There are missing values:

102,Ravi,01/09/2026,

and:

103,Neha,2026-09-03,NA

The empty value and "NA" need to be handled appropriately before numerical analysis.




***3.Rewrite the code to handle missing marks and convert the date column into a suitable date-time format.***



import pandas as pd

df = pd.read_csv(
    "students.csv",
    na_values=["NA", ""]
)

df["Date"] = pd.to_datetime(
    df["Date"],
    dayfirst=True,
    errors="coerce"
)

df["Marks"] = pd.to_numeric(
    df["Marks"],
    errors="coerce"
)

print(df)
print(df.dtypes)

***4.Explain why the value "NA" should be investigated before deciding whether it represents a missing value.***

"NA" may mean "Not Available", but it could also be an actual value or code used by the dataset.

For example:

NA = Not Available

NA = Not Applicable

NA = Student did not attend

NA = Some special category

If we automatically convert "NA" to NaN, we might lose information about what it actually means.

Therefore, we should check the dataset documentation or data source first. If "NA" is confirmed to represent a missing mark, then converting it to NaN is appropriate.


# Q3. A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median. Identify which statistic may better represent a typical employee's salary and justify your choice.

Given code:

import pandas as pd

df = pd.DataFrame({

    "Employee": ["A", "B", "C", "D"],

    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())

print("Median:", df["Salary"].median())



***1.Predict the mean and median salary.***

Mean = Sum of all salaries ÷ Number of employees.

Median = Middle salary after sorting all salaries from lowest to highest.

Because there is an extreme salary, the mean will be higher than the median.


Mean: 2541250.0

Median: 32500.0


***2.Identify the effect of the extreme salary on the mean.***

The extreme salary pulls the mean upward.

This happens because the mean uses every value in the calculation. A very large salary therefore has a strong influence on the result.

The median is much less affected by an extreme value.


***3.Which statistic may better represent a typical employee's salary in this dataset? Justify your answer.***

Median may better represent the typical employee's salary.

Reason: The dataset contains an extreme salary, which makes the mean unusually high. The median represents the middle employee's salary and is more resistant to outliers.

Mean → sensitive to outliers

Median → resistant to outliers




***4.Write code to identify the employee record with the highest salary and explain why the record should be investigated before removing it***

Suppose the DataFrame is called df and the salary column is Salary

We should not immediately remove the highest salary just because it is an outlier.

It could be:

a genuine executive/high-level employee salary

a bonus or special compensation

a legitimate high-paying role

Therefore, we should first verify the employee record and understand why the salary is unusually high. Only if it is confirmed to be an error should we consider correcting or removing it.




In [4]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

highest_salary_employee = df.loc[df["Salary"].idxmax()]

print(highest_salary_employee)


Mean: 2522500.0
Median: 32500.0
Employee           D
Salary      10000000
Name: 3, dtype: object


# Scenario-based Question

# Q1. A student assessment dataset contains missing marks, duplicate student records, inconsistent department names such as IT, it, and I.T., and marks stored as text. Develop a cleaning sequence to standardize the data, handle missing values, remove duplicates, and convert marks into a suitable numeric type. State one risk of deleting missing values without investigating why they are missing.

Data cleaning is the process of correcting missing, duplicate, inconsistent, and incorrectly formatted data. In this dataset, first we investigate and handle missing marks such as blank values, NA, and Absent. Next, duplicate student records are removed using Student_ID. Department names such as IT, it, and I.T. are standardized into a common format. The Marks column is cleaned by removing unnecessary text such as "marks" and converting the values into a numeric type. Finally, the cleaned data should be validated before analysis. Missing values should not be deleted without investigation because they may have meaningful reasons, such as a student being absent, and deleting them blindly can cause information loss and biased results.




In [5]:
import pandas as pd

df = pd.read_csv(r"C:\Users\DELL\Desktop\assignment\student_assessment_dirty.csv")

# 1. Standardize department names
df["Department"] = df["Department"].str.upper()
df["Department"] = df["Department"].str.replace(".", "", regex=False)




# 3. Remove duplicate student records
df = df.drop_duplicates(subset="Student_ID")

# 4. Remove text from marks
df["Marks"] = df["Marks"].str.replace(" marks", "", regex=False)

# 5. Convert Marks into numeric type
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

# 6. Handle missing marks using the mean
mean_marks = df["Marks"].mean()
df["Marks"] = df["Marks"].fillna(mean_marks)
print(df)
print(df.dtypes)

   Student_ID Student_Name Department Assessment  Marks
0        S101         Asha         IT     Python   85.0
1        S102         Ravi         IT     Python   78.0
2        S103         Neha         IT     Python   92.0
3        S104        Karan         HR     Python   74.5
4        S105        Meera         HR     Python   74.5
5        S106        Arjun    FINANCE     Python    0.0
6        S107        Priya    FINANCE     Python   67.0
7        S108        Rahul         IT     Python   75.0
9        S109        Sneha         IT     Python   74.5
10       S110        Varun         HR     Python   88.0
11       S111         Diya    FINANCE     Python   91.0
12       S112         Aman         IT     Python   74.5
13       S113        Nisha         HR     Python   64.0
14       S114        Kabir    FINANCE     Python  105.0
Student_ID          str
Student_Name        str
Department          str
Assessment          str
Marks           float64
dtype: object


***Using Pandas, perform the following cleaning operations in sequence***

***1.Load the CSV file and inspect the dataset using head(), info(), and isnull().sum().***

pd.read_csv() → loads the CSV file into a DataFrame.

head() → displays the first 5 rows.

info() → shows columns, data types, and non-null values.

isnull().sum() → counts the missing values in each column.


In [6]:
import pandas as pd

# Load the CSV file
df = pd.read_csv(r"C:\Users\DELL\Desktop\assignment\student_assessment_dirty.csv")

# Display first 5 rows
display(df.head())

# Display dataset information
display( df.info())

# Check missing values in each column
display( df.isnull().sum())

,Student_ID,Student_Name,Department,Assessment,Marks
0,S101,Asha,IT,Python,85
1,S102,Ravi,it,Python,78
2,S103,Neha,I.T.,Python,92
3,S104,Karan,HR,Python,NaN
4,S105,Meera,HR,Python,Absent


<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str  
 1   Student_Name  15 non-null     str  
 2   Department    15 non-null     str  
 3   Assessment    15 non-null     str  
 4   Marks         12 non-null     str  
dtypes: str(5)
memory usage: 1.0 KB


None

Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64

***2.Standardize department names so that IT, it, and I.T. are represented consistently. Apply the same approach to Finance.***

.str.upper() handles differences like it → IT and finance → FINANCE, while .replace() handles special formats such as I.T..

In [7]:
# Standardize department names
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
    .replace({
        "I.T.": "IT",
        "IT": "IT",
        "FINANCE": "FINANCE",
        "FIN.": "FINANCE"
    })
)

print(df["Department"].unique())

<ArrowStringArray>
['IT', 'HR', 'FINANCE']
Length: 3, dtype: str


***3.Identify and remove exact duplicate student assessment records.***

df.duplicated().sum() → counts the exact duplicate rows.

df[df.duplicated()] → displays the duplicate records.

df.drop_duplicates() → removes the duplicate rows.

The final check confirms that no exact duplicates remain.


In [8]:
# Identify duplicate records
print("Number of duplicate records:", df.duplicated().sum())

# Display duplicate records
print(df[df.duplicated()])

# Remove exact duplicate records
df = df.drop_duplicates()

# Verify that duplicates are removed
print("Duplicates after removal:", df.duplicated().sum())

Number of duplicate records: 1
  Student_ID Student_Name Department Assessment Marks
8       S102         Ravi         IT     Python    78
Duplicates after removal: 0


***4.Convert the Marks column into a numeric format, handling "88 marks", "Absent", "NA", and blank entries appropriately.***

Here, errors="coerce" converts invalid values such as Absent, NA, and blanks into NaN, which can then be handled using the mean in the next step.


In [9]:
# Convert Marks column to numeric
df["Marks"] = (
    df["Marks"]
    .astype(str)
    .str.replace("marks", "", case=False, regex=False)
    .str.strip()
)

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

print(df["Marks"])

0      85.0
1      78.0
2      92.0
3       NaN
4       NaN
5       0.0
6      67.0
7      75.0
9       NaN
10     88.0
11     91.0
12      NaN
13     64.0
14    105.0
Name: Marks, dtype: float64


***5.Investigate missing marks and distinguish absent students from students whose marks have not been entered. State one risk of deleting missing values without investigating why they are missing.***

Deleting all missing-mark records without investigating can remove absent students or a particular group of students, which may lead to biased analysis and incorrect conclusions about student performance.

"Absent" → should be identified separately rather than treating it as an ordinary missing mark.
"NA" or blank → investigate whether the mark was simply not entered.
Only after investigation should we decide how to handle the missing values.


In [10]:
# Check records where Marks are missing
missing_marks = df[df["Marks"].isnull()]

print(missing_marks)

   Student_ID Student_Name Department Assessment  Marks
3        S104        Karan         HR     Python    NaN
4        S105        Meera         HR     Python    NaN
9        S109        Sneha         IT     Python    NaN
12       S112         Aman         IT     Python    NaN


***6.Identify marks outside the valid range of 0–100 and decide how they should be handled***

First, find marks that are less than 0 or greater than 100

If invalid values are found, convert them to NaN so they can be investigated or handled appropriately but there are no invalid values in this dataset

In [11]:
# Identify invalid marks
invalid_marks = df[(df["Marks"] < 0) | (df["Marks"] > 100)]

print("Invalid marks:")
print(invalid_marks)


Invalid marks:
   Student_ID Student_Name Department Assessment  Marks
14       S114        Kabir    FINANCE     Python  105.0


***7.Display the cleaned DataFrame and report the number of records removed, missing marks remaining, and invalid marks identified***

In [12]:
# Number of records before removing duplicates
records_before = len(df)

# Remove exact duplicates
df = df.drop_duplicates()

# Number of records removed
records_removed = records_before - len(df)

# Identify invalid marks (outside 0–100)
invalid_marks = df[(df["Marks"] < 0) | (df["Marks"] > 100)]

# Count invalid marks
invalid_count = len(invalid_marks)

# Handle invalid marks by converting them to NaN
df.loc[(df["Marks"] < 0) | (df["Marks"] > 100), "Marks"] = pd.NA

# Handle missing marks using mean
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

# Count missing marks remaining
missing_remaining = df["Marks"].isnull().sum()

# Display cleaned DataFrame
print("Cleaned DataFrame:")
print(df)

# Report cleaning results
print("\n--- Cleaning Report ---")
print("Records removed:", records_removed)
print("Missing marks remaining:", missing_remaining)
print("Invalid marks identified:", invalid_count)

Cleaned DataFrame:
   Student_ID Student_Name Department Assessment      Marks
0        S101         Asha         IT     Python  85.000000
1        S102         Ravi         IT     Python  78.000000
2        S103         Neha         IT     Python  92.000000
3        S104        Karan         HR     Python  71.111111
4        S105        Meera         HR     Python  71.111111
5        S106        Arjun    FINANCE     Python   0.000000
6        S107        Priya    FINANCE     Python  67.000000
7        S108        Rahul         IT     Python  75.000000
9        S109        Sneha         IT     Python  71.111111
10       S110        Varun         HR     Python  88.000000
11       S111         Diya    FINANCE     Python  91.000000
12       S112         Aman         IT     Python  71.111111
13       S113        Nisha         HR     Python  64.000000
14       S114        Kabir    FINANCE     Python  71.111111

--- Cleaning Report ---
Records removed: 0
Missing marks remaining: 0
Invalid ma